apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
    env: qa
  name: flask-app
  namespace: mlops
spec:
  replicas: 2 # Creating two PODs for our app
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
        env: qa
    spec:
      containers:
      - image: pikkaayflaskapp.azurecr.io/flaskappdockerapi:latest # Docker image name, that we pushed to GCR
        name: flaskapp-pod    # POD name 
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
          - name: flaskapp-secret
